language: generic
dist: xenial
sudo: required
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache:
  directories:
    - $HOME/.cache/pip
addons:
  postgresql: "9.6"
services:
  - docker
  - postgresql
  - redis-server

# stage decl.
stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix for test stage
os:
  - linux
env:
  global:
    - BACKEND_ETCD_ADDR=localhost:2379
    - BACKEND_NAMESPACE=testing
    - BACKEND_REDIS_ADDR=localhost:6379
    - BACKEND_DB_ADDR=localhost:5432
    - BACKEND_DB_USER=postgres
    - BACKEND_DB_PASSWORD=
    - BACKEND_DB_NAME=testing

addons:
  apt:
    packages:
    - libsnappy-dev

# default test job
before_install:
  - type -t deactivate && deactivate || true
  - export PATH=/opt/python/3.6/bin:$PATH
install:
  - if [[ $TRAVIS_BRANCH == "develop" ]]; then BRANCH="develop"; else BRANCH="master"; fi
  # install backend.ai-agent
  - |
    python -m venv ~/virtualenv/agent
    source ~/virtualenv/agent/bin/activate
    pip install -U pip setuptools
    sed -i'' -e "s/{BRANCH}/$BRANCH/g" requirements-ci.txt
    pip install -U --upgrade-strategy=eager -r requirements-ci.txt
before_script:
  # load etcd server
  - mkdir -p /tmp/etcd
  - mkdir -p /tmp/vfolders
  - docker run -d -p 2379:2379 -p 2380:2380 --name backendai-etcd
     -v /tmp/etcd:/etcd-data
     quay.io/coreos/etcd:v3.2.8
     /usr/local/bin/etcd
     --name backendai-etcd
     --data-dir /etcd-data
     --listen-client-urls http://0.0.0.0:2379
     --advertise-client-urls http://0.0.0.0:2379
     --listen-peer-urls http://0.0.0.0:2380
     --initial-advertise-peer-urls http://0.0.0.0:2380
     --initial-cluster backendai-etcd=http://0.0.0.0:2380
     --initial-cluster-token backendai-etcd-token
     --initial-cluster-state new
     --auto-compaction-retention 1
script:
  - source ~/virtualenv/agent/bin/activate; python -m flake8 src tests
  - sudo bash -c 'source ~/virtualenv/agent/bin/activate; python -m pytest --cov=src'
after_success:
  - codecov
after_script:
  - killall -9 python

# stage def.
jobs:
  include:
    - stage: deploy
      before_install:
        - PYTHON_VERSION=3.6 ./scripts/ci/overwrite-python.sh
      install: skip
      script: skip
      after_script: skip
      deploy:
        on:
          tags: true
        provider: script
        script: ./scripts/ci/deploy.sh

notifications:
  webhooks:
    secure: "TT5qgI/QCVuBHmBgI89i9krQGY6scCk8138jBtPGVORj6yHx8pljk3ROJ/EwxxY560ywiWqtxak8SpfO5JwmBqG35cO7OAQMSPhCdtTKL2E25EalJs8MXlzmPm8S7hp4eAUUeBFscH7KzBm824ncvxWFU3FuAk0ZrTGmCeUn4XFjL3TYkfjrE0Oe6TqZUr1tpVh7yk7StEJFjun5uzVCG6uRWjvlbNnULmJEU3Yf0W7u8/cBYqqVOkOCuVKIZKZexuUDT7Tm39XKyacHFcJ4TCzeBo5kYRusudoHHVfWThE4cevtUvWN9HjuGBpF5RXTHESd/nu7P+Wcb9Zgk1+WyeAO1S3v0c/+FYdcmUculGjNtrTSvzrs6F7HWIkn5fuFuuj0b7oLh/lHu3j75Qqr0CPNkTFLhQIwpOR/aWjPeKg0XIQCFGaCSuJqh9Sw5QSBqoBDNwU6+TW8Bq98519B41oWFO1pKD3VvNcy1HANVror1KgqNoJj9K35lonXVsl5384JMRQCO0hH1GIZWY9Nk2ljq+VT5PGOai5qQ7KKRCE7lIJwjGIxwdrBlDzepMvUL8dHtZfANTTZ8SiqSQ+woAR9iRZlKw2jyyJ/hdzhtXtcnANU5hDSRrsV8Q7nxpM9BJBROZnKMIG0z+oUoDQ5KFbDJHRWeL7H9zTuw+V//ZQ="
