language: python
dist: xenial
sudo: required
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache:
  directories:
    - $HOME/.cache/pip
addons:
  postgresql: "9.6"
services:
  - docker
  - postgresql
  - redis-server
addons:
  apt:
    packages:
    - libsnappy-dev

# stage decl.
stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix for test stage
os:
  - linux
env:
  global:
    - BACKEND_ETCD_ADDR=localhost:2379
    - BACKEND_NAMESPACE=testing
    - BACKEND_REDIS_ADDR=localhost:6379
    - BACKEND_DB_ADDR=localhost:5432
    - BACKEND_DB_USER=postgres
    - BACKEND_DB_PASSWORD=
    - BACKEND_DB_NAME=testing
python:
  - "3.6"

# default test job
before_install:
  # escape from TravisCI's default virtualenv
  - type -t deactivate && deactivate || true
  - export PATH=/opt/python/3.6/bin:$PATH
install:
  - if [[ $TRAVIS_BRANCH == "develop" ]]; then BRANCH="develop"; else BRANCH="master"; fi
  # install backend.ai-agent
  - |
    python -m venv ~/virtualenv/agent
    source ~/virtualenv/agent/bin/activate
    pip install -U pip setuptools
    sed -i'' -e "s/{BRANCH}/$BRANCH/g" requirements-ci.txt
    pip install -U -r requirements-ci.txt
before_script:
  # load etcd server
  - mkdir -p /tmp/etcd
  - mkdir -p /tmp/vfolders
  - docker run -d -p 2379:2379 -p 2380:2380 --name backendai-etcd
     -v /tmp/etcd:/etcd-data
     quay.io/coreos/etcd:v3.3.9
     /usr/local/bin/etcd
     --name backendai-etcd
     --data-dir /etcd-data
     --listen-client-urls http://0.0.0.0:2379
     --advertise-client-urls http://0.0.0.0:2379
     --listen-peer-urls http://0.0.0.0:2380
     --initial-advertise-peer-urls http://0.0.0.0:2380
     --initial-cluster backendai-etcd=http://0.0.0.0:2380
     --initial-cluster-token backendai-etcd-token
     --initial-cluster-state new
     --auto-compaction-retention 1
script:
  - source ~/virtualenv/agent/bin/activate; python -m flake8 src tests
  - sudo bash -c 'source ~/virtualenv/agent/bin/activate; python -m pytest --cov=src'
after_success:
  - codecov
after_script:
  - killall -9 python

# stage def.
jobs:
  include:
    - stage: test

    - stage: deploy
      python: "3.6"
      before_install: skip
      install: skip
      before_script: skip
      script: skip
      after_script: skip
      deploy:
        on:
          tags: true
        provider: pypi
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        user: lablup
        password:
          secure: "TdL1VbJ/eLyFT3Aq9xz9M7m6c2At5BgLoKYEjjQB0mCo67aTrI8M2japAQ7wafVeBGGP4Mo8nnY+90tjmINg/x8bXvxCv7avEf9eq0HU6u+DIgeTYVPtZMNRbPWl8z7MPxOQBIwwszSV0dw9EHHTx14oSKtEnd9v9210+HJJtnNujo00QiNgU8NQVqAcBKCMyrqAeNlG4K0clZ1sD77W58gfCYfbIcYXNFV7n/J8ke/aSyBnow/n4JSj9kDUJgOojfg8jQ+d0/sUFxaYoaakvozz6zGvlRm57+NlBic1onMrHF7nuOLBFNDZguMTuemxDXqv7fZXp2QATA7u9WZtS2kW3alebQcbXq+SW9omG8uhbhHRkPiXMBUPvBz59fMPvy29zpN6b7f+ihA9QP47zi4pt6N6Z7Xovm3R+RctTSqZkWqc47eajVWZRevJ5Iw68woF0/p1w6pGm84eWonJDUlmofuwcmeYduj+J+y5bEPt9gHdUKM14uzhWQzsiV4NkapTWoX2IGILp/svJUTUrB2D7BrUrPKZ3NLKFjlVdXmhJZdcZ6ovsxh8C+Ls3i+fDAd3TKxy0TugwKXYScs26vRWcLx8mRlDCoY/BFyb7LtzDv/4/vyHvmJBY9XTxoz7PJRV1C2zUK1XOXjbh4iy4SYNIDB70izlswetRUgKlNQ="

notifications:
  webhooks:
    secure: "TT5qgI/QCVuBHmBgI89i9krQGY6scCk8138jBtPGVORj6yHx8pljk3ROJ/EwxxY560ywiWqtxak8SpfO5JwmBqG35cO7OAQMSPhCdtTKL2E25EalJs8MXlzmPm8S7hp4eAUUeBFscH7KzBm824ncvxWFU3FuAk0ZrTGmCeUn4XFjL3TYkfjrE0Oe6TqZUr1tpVh7yk7StEJFjun5uzVCG6uRWjvlbNnULmJEU3Yf0W7u8/cBYqqVOkOCuVKIZKZexuUDT7Tm39XKyacHFcJ4TCzeBo5kYRusudoHHVfWThE4cevtUvWN9HjuGBpF5RXTHESd/nu7P+Wcb9Zgk1+WyeAO1S3v0c/+FYdcmUculGjNtrTSvzrs6F7HWIkn5fuFuuj0b7oLh/lHu3j75Qqr0CPNkTFLhQIwpOR/aWjPeKg0XIQCFGaCSuJqh9Sw5QSBqoBDNwU6+TW8Bq98519B41oWFO1pKD3VvNcy1HANVror1KgqNoJj9K35lonXVsl5384JMRQCO0hH1GIZWY9Nk2ljq+VT5PGOai5qQ7KKRCE7lIJwjGIxwdrBlDzepMvUL8dHtZfANTTZ8SiqSQ+woAR9iRZlKw2jyyJ/hdzhtXtcnANU5hDSRrsV8Q7nxpM9BJBROZnKMIG0z+oUoDQ5KFbDJHRWeL7H9zTuw+V//ZQ="
