version: '2'
services:
  sorna-agent:
    image: python:3.6
    depends_on:
      - docker
      - etcd
    volumes:
      - ".:/usr/src/sorna-agent"
    working_dir: "/usr/src/sorna-agent"
    environment:
      DOCKER_HOST: "http://docker:2375"
      ETCD_ADDR: "etcd:2379"
    command: ./run-ci-tests.sh
  docker:
    image: docker:dind
    privileged: true
  etcd:
    image: quay.io/coreos/etcd
